Repository The-Final-Nights/The-Final-Nights, pull requests merged in 2025-05, with the labels that each got.

#375 Experience code small rework
  code/controllers/subsystem/city_time.dm
Labels: Enhancement, Balance

#334 Defib Patch 2: E.B. [HOTFIX]
  code/datums/mind.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/vtmb/dharma.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/vtmb/vampire_clane/clane.dm
Labels: Enhancement, Balance, Stale

#377 3 Hour Round Timer
  code/controllers/subsystem/city_time.dm
Labels: Enhancement

#392 changelog now functions take 2
  .github/workflows/compile_changelogs.yml
Labels: Enhancement, Testing Evidence Required, Development

#397 adds literally one letter to the code I did last night
  code/modules/wod13/wallcode.dm
Labels: Enhancement

#403 New Title Image
  config/title_screens/images/vampire.png
Labels: Enhancement, Icons

#398 Gives the Baron the Punk Jacket
  code/modules/vtmb/jobs/anarchs/baron.dm
  code/modules/vtmb/jobs/primogen.dm
Labels: Enhancement, Balance

#351 Dom/Pres hearing checks and Dom 1 custom command
  code/modules/wod13/datums/powers/discipline/dementation.dm
  code/modules/wod13/datums/powers/discipline/dominate.dm
  code/modules/wod13/datums/powers/discipline/presence.dm
Labels: Enhancement, TESTMERGE, Balance

#406 Suck Weed Everynight
  code/modules/wod13/items/narcotics/bweedpack.dm
  code/modules/wod13/packadulteration.dm
  tgstation.dme
Labels: New Feature

#381 Changes sanitize_hexcolor to use 6 characters by default
  code/__DEFINES/cult.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/sanitize_values.dm
  code/__HELPERS/text.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_onclick/hud/fullscreen.dm
  code/game/machinery/limbgrower.dm
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  code/game/objects/items/dyekit.dm
  code/game/objects/structures/dresser.dm
  code/game/objects/structures/mirror.dm
  code/modules/admin/create_mob.dm
  code/modules/antagonists/cult/cult.dm
  code/modules/antagonists/fugitive/fugitive_outfits.dm
  code/modules/awaymissions/corpse.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/outfits/event.dm
  code/modules/mining/lavaland/necropolis_chests.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/research/xenobiology/xenobiology.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/bodyparts/helpers.dm
  code/modules/surgery/organs/tails.dm
  code/modules/wod13/datums/bouncer_roles/bouncer_mob_role.dm
  code/modules/wod13/datums/powers/discipline/vicissitude.dm
  code/modules/wod13/npc.dm
  code/modules/wod13/npcroles.dm
Labels: Enhancement, TESTMERGE

#300 Cruelty and Lead
  code/modules/projectiles/projectile.dm
  code/modules/wod13/ammostack.dm
  code/modules/wod13/datums/powers/discipline/quietus.dm
  code/modules/wod13/guns.dm
Labels: Enhancement, TESTMERGE, Balance

#359 Melee Stronk
  code/modules/wod13/melee.dm
Labels: Enhancement, TESTMERGE, Balance

#368 Tzimisce "Four arms" vissi upgrade no longer delimbs you of an extra arm when unupgraded.
  code/modules/mob/inventory.dm
  code/modules/wod13/datums/powers/discipline/vicissitude.dm
Labels: Enhancement

#409 Garou Renown Fix Hopefully
  code/modules/client/preferences_savefile.dm
Labels: Enhancement, FUCK

#410 Domination is Quieter
  code/modules/wod13/datums/powers/discipline/dominate.dm
Labels: Enhancement

#412 (Comm) Resprite Gangrel in-hand.
  code/modules/wod13/lefthand.dmi
  code/modules/wod13/righthand.dmi
  code/modules/wod13/weapons.dmi
Labels: Enhancement, Icons

#343 Coffee & Tea in Soda Dispensers
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Labels: Enhancement

#418 Presence users gain charmer trait
  code/modules/wod13/datums/powers/discipline/presence.dm
Labels: Enhancement

#370 Disables minimum character age restriction for jobs
  code/modules/vtmb/jobs/anarchs/baron.dm
  code/modules/vtmb/jobs/giovanni.dm
  code/modules/vtmb/jobs/primogen.dm
  code/modules/vtmb/jobs/prince.dm
  code/modules/vtmb/jobs/regent.dm
  code/modules/vtmb/jobs/sheriff.dm
  code/modules/vtmb/jobs/voivode.dm
Labels: Enhancement

#372 Endron Paperwork Templates
  config/blanks.json
Labels: Enhancement

#427 Makes the CI/CD checks gain the ability to download byond again
  tools/ci/download_byond.sh
Labels: Development

#423 Gangrel Claw Buff + Other Tweaks
  code/modules/wod13/datums/powers/discipline/protean.dm
  code/modules/wod13/melee.dm
Labels: Enhancement, Balance

#405 Not all ids are publicly identifiable
  code/game/objects/items/cards_ids.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/vtmb/jobs/jobs.dm
Labels: Enhancement

#428 Fixes the chem suit sprite on slim characters
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: Enhancement, Icons

#432 Individual silver bullets are no longer invisible.
  code/modules/wod13/ammostack.dm
Labels: Enhancement

#380 [MAPPING] Endron Corporate Headquarters, The Sequel
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/jobs/garou/poisonshore.dm
  code/modules/wod13/ambient.dm
  code/modules/wod13/datums/bouncer_roles/bouncer_endron_role.dm
  code/modules/wod13/effects/endron_barrier.dm
  code/modules/wod13/npcroles.dm
  code/modules/wod13/npcs/bouncer_endron.dm
  tgstation.dme
Labels: Enhancement, TESTMERGE, Mapping

#401 Endron phones start with numbers
  code/_globalvars/phonesnumbers.dm
  code/modules/vtmb/electronics/phones/phone.dm
  code/modules/vtmb/electronics/phones/phone_contact.dm
  code/modules/vtmb/jobs/garou/poisonshore.dm
Labels: Enhancement

#400 Endron Employee Alternate Titles
  modular_tfn/modules/alt_job_titles/alt_job_titles.dm
  modular_tfn/modules/alt_job_titles/outfits.dm
Labels: Enhancement

#366 SFPD: Duty belts, Utility uniforms, and SWAT changes.
  code/game/objects/items/storage/belt.dm
  code/modules/vtmb/gridventory.dm
  code/modules/vtmb/jobs/police.dm
  code/modules/vtmb/jobs/swat.dm
  code/modules/wod13/clothing.dmi
  code/modules/wod13/items/clothes/belt.dm
  code/modules/wod13/items/clothes/under.dm
  code/modules/wod13/machine_vending.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/worn.dmi
  icons/mob/clothing/belt.dmi
  icons/obj/clothing/belts.dmi
Labels: Enhancement, Balance

#429 Ties Voice of Domination to Dominate 5
  code/modules/wod13/datums/powers/discipline/dominate.dm
Labels: Enhancement, Balance

#434 Genderless Underwear
  code/modules/mob/dead/new_player/sprite_accessories.dm
Labels: Enhancement

#426 Implements vampire-age job restrictions
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/vtmb/jobs/anarchs/baron.dm
  code/modules/vtmb/jobs/giovanni.dm
  code/modules/vtmb/jobs/primogen.dm
  code/modules/vtmb/jobs/prince.dm
  code/modules/vtmb/jobs/regent.dm
  code/modules/vtmb/jobs/sheriff.dm
  code/modules/vtmb/jobs/voivode.dm
Labels: Enhancement

#253 Adds loadout
  code/__HELPERS/_lists.dm
  code/__HELPERS/sanitize_values.dm
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/items/toys.dm
  code/game/world.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/mob.dm
  code/modules/wod13/items/clothes/suit.dm
  code/modules/wod13/items/stores/clothes.dm
  config/game_options.txt
  html/browser/common.css
  modular_tfn/code/modules/client/preferences.dm
  modular_tfn/modules/loadout/_loadout.dm
  modular_tfn/modules/loadout/loadout_eyewear.dm
  modular_tfn/modules/loadout/loadout_footwear.dm
  modular_tfn/modules/loadout/loadout_general.dm
  modular_tfn/modules/loadout/loadout_gloves.dm
  modular_tfn/modules/loadout/loadout_hat.dm
  modular_tfn/modules/loadout/loadout_neck.dm
  modular_tfn/modules/loadout/loadout_suit.dm
  modular_tfn/modules/loadout/loadout_uniform.dm
  tgstation.dme
Labels: Enhancement, New Feature, TESTMERGE, Config

#361 FBI Agent Touch Up and Buff
  code/game/objects/items/storage/briefcase.dm
  code/modules/vtmb/jobs/fbi.dm
  code/modules/wod13/ammostack.dm
  code/modules/wod13/cargo.dm
  code/modules/wod13/guns.dm
  code/modules/wod13/items/clothes/suit.dm
  code/modules/wod13/onfloor.dmi
  tgstation.dme
Labels: Enhancement, New Feature, Balance

#439 Fixes several complaining lints
  code/datums/components/construction.dm
  code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
  code/modules/admin/permissionedit.dm
  code/modules/clothing/chameleon.dm
  code/modules/events/swarmer.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
Labels: Enhancement

#394 Punch Damage for Homid
  code/modules/vtmb/werewolf_species.dm
Labels: Enhancement, Balance

#444 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Enhancement, Testing Evidence Required, Development

#319 Daimonion Rework take two!
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/living.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/wod13/datums/curses/__curse.dm
  code/modules/wod13/datums/curses/daimonion_curses.dm
  code/modules/wod13/datums/powers/discipline/daimonion.dm
  code/modules/wod13/onyxcombat.dm
  tgstation.dme
Labels: Enhancement, Balance

#445 Resprites Medkits.
  code/game/objects/items/storage/firstaid.dm
  code/modules/wod13/onfloor.dmi
  icons/obj/storage.dmi
Labels: Enhancement, Icons

#443 Fixes cop car lights spam
  code/modules/wod13/car.dm
Labels: Enhancement

#454 Fix tgui list input windows bug
  tgui/packages/tgui/interfaces/ListInputModal.tsx
Labels: Enhancement

#389 The Woof Among Us (some garou tweaks)
  code/modules/mob/living/carbon/werewolf/lupus.dm
  code/modules/mob/living/carbon/werewolf/werewolf.dm
  code/modules/mob/living/carbon/werewolf/werewolf_defense.dm
  code/modules/vtmb/werewolf/gifts.dm
Labels: Enhancement, Balance

#441 Decapitation is only an intentional timed action, no longer simply at random through damage
  code/datums/components/butchering.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/surgery/bodyparts/head.dm
Labels: Enhancement, Balance

#435 Debtor quirk now works, Ventrue money changed
  code/modules/vtmb/electronics/atms/atm.dm
  code/modules/vtmb/jobs/jobs.dm
  code/modules/wod13/quirks.dm
Labels: Enhancement, Balance

#422 Phone contact networks implemented, leaders and sect members have each other's phone contacts
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/_globalvars/contacts.dm
  code/_globalvars/phonesnumbers.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/living_defines.dm
  code/modules/vtmb/electronics/phones/phone.dm
  code/modules/vtmb/electronics/phones/phone_contact.dm
  code/modules/vtmb/ghoul_species.dm
  code/modules/vtmb/jobs/anarchs/baron.dm
  code/modules/vtmb/jobs/anarchs/bouncer.dm
  code/modules/vtmb/jobs/anarchs/emissary.dm
  code/modules/vtmb/jobs/anarchs/sweeper.dm
  code/modules/vtmb/jobs/bloodlines/lasombra.dm
  code/modules/vtmb/jobs/bogatyr.dm
  code/modules/vtmb/jobs/dealer.dm
  code/modules/vtmb/jobs/fbi.dm
  code/modules/vtmb/jobs/gargoyle.dm
  code/modules/vtmb/jobs/garou/amberglade.dm
  code/modules/vtmb/jobs/garou/paintedcity.dm
  code/modules/vtmb/jobs/garou/poisonshore.dm
  code/modules/vtmb/jobs/giovanni.dm
  code/modules/vtmb/jobs/hound.dm
  code/modules/vtmb/jobs/police.dm
  code/modules/vtmb/jobs/priest.dm
  code/modules/vtmb/jobs/primogen.dm
  code/modules/vtmb/jobs/prince.dm
  code/modules/vtmb/jobs/regent.dm
  code/modules/vtmb/jobs/seneschal.dm
  code/modules/vtmb/jobs/sheriff.dm
  code/modules/vtmb/jobs/triad.dm
  code/modules/vtmb/jobs/voivode.dm
  code/modules/vtmb/jobs/zadruga.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/vtmb/kuei_jin.dm
  code/modules/vtmb/werewolf_species.dm
  code/modules/wod13/onfloor.dm
  tgstation.dme
Labels: Enhancement, Balance, Mapping

#404 Tzimisce Rework Part 1
  code/modules/surgery/organs/augments_arms.dm
  code/modules/vtmb/vampire_clane/tzimisce.dm
  code/modules/wod13/datums/powers/discipline/vicissitude.dm
  code/modules/wod13/melee.dm
Labels: Enhancement, New Feature, Balance

#396 Refactors auspex 5 avatars
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/sight.dm
  code/__HELPERS/game.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/mobs.dm
  code/_onclick/hud/fullscreen.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/dead/observer/auspex_avatar/auspex_avatar.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_lists.dm
  code/modules/mob/mob_say.dm
  code/modules/wod13/datums/powers/discipline/auspex.dm
  icons/effects/static.dmi
  tgstation.dme
Labels: Enhancement, Removal

#462 PROPERLY makes our CI/CD checks work again. This time under nimi's guidance.
  Dockerfile
  tools/ci/install_byond.sh
Labels: Enhancement, Development

#461 Ports IC verb to toggle underwear/shirt/socks visibilty on/off.
  code/__DEFINES/tfn/vtm_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Enhancement

#464 hopefully fixes maps
  code/__DEFINES/dcs/signals.dm
  code/_globalvars/contacts.dm
  code/modules/vtmb/electronics/phones/phone.dm
Labels: Enhancement, FUCK, Development

#446 Discipline power groups cannot be active at the same time
  code/__DEFINES/wod13/dcs/power_signals.dm
  code/__DEFINES/wod13/discipline.dm
  code/modules/wod13/datums/powers/discipline/__discipline.dm
  code/modules/wod13/datums/powers/discipline/__discipline_power.dm
  code/modules/wod13/datums/powers/discipline/celerity.dm
  code/modules/wod13/datums/powers/discipline/fortitude.dm
  code/modules/wod13/datums/powers/discipline/obfuscate.dm
  code/modules/wod13/datums/powers/discipline/potence.dm
Labels: Enhancement, Refactor, Balance

#458 Preference to hide flavor text when hiding your face!
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_say.dm
  modular_tfn/code/modules/mob/living/carbon/human/human_defines.dm
Labels: New Feature

#358 Voice concealment: The Second Coming.
  code/modules/clothing/masks/_masks.dm
  code/modules/mob/living/carbon/human/human_say.dm
Labels: Enhancement, Balance, Stale

#437 Renames a couple of cards in the tarot deck.
  code/modules/games/tarot.dm
  icons/obj/toy.dmi
Labels: Enhancement

#460 NPC attacks now properly work.
  code/__DEFINES/dcs/signals.dm
  code/modules/antagonists/blob/blob_mobs.dm
  code/modules/antagonists/morph/morph.dm
  code/modules/mining/minebot.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/eldritch_demons.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/friendly/snake.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/mob/living/simple_animal/guardian/types/assassin.dm
  code/modules/mob/living/simple_animal/guardian/types/explosive.dm
  code/modules/mob/living/simple_animal/guardian/types/fire.dm
  code/modules/mob/living/simple_animal/guardian/types/gravitokinetic.dm
  code/modules/mob/living/simple_animal/guardian/types/lightning.dm
  code/modules/mob/living/simple_animal/guardian/types/ranged.dm
  code/modules/mob/living/simple_animal/guardian/types/standard.dm
  code/modules/mob/living/simple_animal/guardian/types/support.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
  code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
  code/modules/mob/living/simple_animal/hostile/headcrab.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/illusion.dm
  code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
  code/modules/mob/living/simple_animal/hostile/jungle/mook.dm
  code/modules/mob/living/simple_animal/hostile/jungle/seedling.dm
  code/modules/mob/living/simple_animal/hostile/mecha_pilot.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/swarmer.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
  code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
  code/modules/mob/living/simple_animal/hostile/regalrat.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/space_dragon.dm
  code/modules/mob/living/simple_animal/hostile/statue.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
  code/modules/swarmers/swarmer.dm
Labels: Enhancement, TESTMERGE, Balance

#478 Fixes Kindred Citizen Oversight
  code/modules/vtmb/jobs/citizen.dm
Labels: Enhancement, Balance

#481 KJ Quirk Bugfix
  code/modules/wod13/quirks.dm
Labels: Enhancement

#485 CI scripts! V3!
  Dockerfile
  tools/ci/download_byond.sh
  tools/ci/install_byond.sh
Labels: Enhancement, Development

#419 Warrior Salubri PR (and Added Third Eyes to Salubris and minor edit to Healer Salubri)
  code/__DEFINES/tfn/vtm_defines.dm
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/__DEFINES/wod13/status_effects_debuffs.dm
  code/_globalvars/traits/_traits.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/init_signals.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/vtmb/jobs/anarchs/bouncer.dm
  code/modules/vtmb/jobs/anarchs/emissary.dm
  code/modules/vtmb/jobs/anarchs/sweeper.dm
  code/modules/vtmb/jobs/bloodlines/salubri.dm
  code/modules/vtmb/jobs/doctor.dm
  code/modules/vtmb/jobs/graveyard_keeper.dm
  code/modules/vtmb/jobs/janitor.dm
  code/modules/vtmb/jobs/priest.dm
  code/modules/vtmb/jobs/stripper.dm
  code/modules/vtmb/jobs/taxi.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/vtmb/magic/pyramid.dm
  code/modules/vtmb/vampire_clane/clane.dm
  code/modules/vtmb/vampire_clane/salubri.dm
  code/modules/vtmb/vampire_clane/salubri_warrior.dm
  code/modules/wod13/UI/actions.dmi
  code/modules/wod13/bloodsucking.dm
  code/modules/wod13/datums/powers/discipline/healer_valeren.dm
  code/modules/wod13/datums/powers/discipline/warrior_valeren.dm
  code/modules/wod13/status_effects/debuffs.dm
  modular_tfn/modules/morality/morality.dm
  tgstation.dme
Labels: New Feature, TESTMERGE

#487 CICD checks! v4
  Dockerfile
  dependencies.sh
  tools/ci/download_byond.sh
  tools/ci/install_byond.sh
Labels: Enhancement, FUCK, Development

#489 Unwhitelists the FBI
  code/modules/vtmb/jobs/fbi.dm
Labels: Balance, Lore Team Approved

#472 Ports Examine Blocks from TG
  code/__DEFINES/mobs.dm
  code/__DEFINES/span.dm
  code/_onclick/hud/alert.dm
  code/datums/components/mood.dm
  code/datums/mind.dm
  code/game/atoms.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/buildmode/submodes/advanced.dm
  code/modules/buildmode/submodes/area_edit.dm
  code/modules/buildmode/submodes/basic.dm
  code/modules/buildmode/submodes/boom.dm
  code/modules/buildmode/submodes/copy.dm
  code/modules/buildmode/submodes/delete.dm
  code/modules/buildmode/submodes/fill.dm
  code/modules/buildmode/submodes/mapgen.dm
  code/modules/buildmode/submodes/outfit.dm
  code/modules/buildmode/submodes/smite.dm
  code/modules/buildmode/submodes/throwing.dm
  code/modules/buildmode/submodes/variable_edit.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/silicon/ai/examine.dm
  code/modules/mob/living/silicon/laws.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/mob/mob.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
Labels: Enhancement, TESTMERGE

#421 ports some laughing sounds from azure-peak, emote changes
  code/datums/emotes.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/simple_animal/hostile/netherworld.dm
  code/modules/photography/photos/photo.dm
  sound/mobs/humanoids/human/giggle/female_giggle_1.ogg
  sound/mobs/humanoids/human/giggle/female_giggle_2.ogg
  sound/mobs/humanoids/human/giggle/female_giggle_3.ogg
  sound/mobs/humanoids/human/giggle/female_giggle_4.ogg
  sound/mobs/humanoids/human/laugh/chuckle/female_chuckle_1.ogg
  sound/mobs/humanoids/human/laugh/chuckle/female_chuckle_2.ogg
  sound/mobs/humanoids/human/laugh/chuckle/female_chuckle_3.ogg
  sound/mobs/humanoids/human/laugh/chuckle/male_chuckle_1.ogg
  sound/mobs/humanoids/human/laugh/crazy/female_crazylaugh_1.ogg
  sound/mobs/humanoids/human/laugh/crazy/female_crazylaugh_2.ogg
  sound/mobs/humanoids/human/laugh/crazy/male_crazylaugh_1.ogg
  sound/mobs/humanoids/human/laugh/crazy/male_crazylaugh_2.ogg
  sound/mobs/humanoids/human/laugh/crazy/male_crazylaugh_3.ogg
  sound/mobs/humanoids/human/laugh/crazy/male_crazylaugh_4.ogg
  sound/mobs/humanoids/human/laugh/female_laugh_1.ogg
  sound/mobs/humanoids/human/laugh/female_laugh_2.ogg
  sound/mobs/humanoids/human/laugh/male_laugh_1.ogg
  sound/mobs/humanoids/human/laugh/male_laugh_2.ogg
  sound/mobs/humanoids/human/sigh/female_sigh_1.ogg
  sound/mobs/humanoids/human/sigh/female_sigh_2.ogg
  sound/mobs/humanoids/human/sigh/female_sigh_3.ogg
  sound/mobs/humanoids/human/sigh/male_sigh_1.ogg
  sound/mobs/humanoids/human/sigh/male_sigh_2.ogg
  sound/mobs/humanoids/human/sigh/male_sigh_3.ogg
Labels: Enhancement, New Feature, TESTMERGE, Sounds

#507 Update init_signals.dm for Salubri eye traits runtime fix
  code/modules/mob/living/carbon/human/init_signals.dm
Labels: Enhancement

#452 Handheld Tasers and Pepperspray for the gun store.
  code/game/objects/items/stunbaton.dm
  code/modules/wod13/items/stores/guns.dm
  code/modules/wod13/onfloor.dmi
  modular_tfn/modules/taser_tfn13/taser.dmi
  sound/wod13/electric_zap.ogg
  sound/wod13/handtaser_activate.ogg
Labels: Enhancement, TESTMERGE, Balance

#496 Protean Rank 1 Changes your Eye Color now
  code/modules/wod13/datums/powers/discipline/protean.dm
Labels: Enhancement

#482 Latin & Lively Aura Cost Reduction
  code/modules/wod13/quirks.dm
Labels: Enhancement, Balance

#339 New Anarch Bar, Base, and Garage Addition And Radios (And Knuckles)
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/electronics/p25.dm
  code/modules/vtmb/jobs/anarchs/baron.dm
  code/modules/vtmb/jobs/anarchs/bouncer.dm
  code/modules/vtmb/jobs/anarchs/emissary.dm
  code/modules/vtmb/jobs/anarchs/sweeper.dm
  code/modules/wod13/Posters.dmi
  code/modules/wod13/ambient.dm
  code/modules/wod13/posters.dm
  code/modules/wod13/tiles.dmi
  code/modules/wod13/wallcode.dm
  tgstation.dme
Labels: Enhancement, Mapping
