Repository The-Final-Nights/The-Final-Nights, pull requests merged in 2025-09, with the labels that each got.

#769 Salubri Discipline Normalization
  code/modules/client/preferences.dm
Labels: TESTMERGE, Balance, Removal, Lore Team Approved

#772 rules based text for the blood bond
  modular_tfn/modules/vitae/code/ghouling.dm
Labels: Enhancement, TESTMERGE

#774 Fixes the FBI dutyvest
  code/modules/wod13/clothing.dmi
  code/modules/wod13/items/clothes/suit.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/worn.dmi
  modular_tfn/modules/sfpd_gear/code/policeoutfits.dm
  modular_tfn/modules/sfpd_gear/icons/clothing.dmi
  modular_tfn/modules/sfpd_gear/icons/onfloor.dmi
  modular_tfn/modules/sfpd_gear/icons/worn.dmi
Labels: Icons

#680 Adds thinblood merit
  code/__DEFINES/traits/vtm/declarations.dm
  code/__DEFINES/traits/vtm/sources.dm
  code/controllers/subsystem/city_time.dm
  code/datums/quirks/_quirk.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/vtmb/frenzy.dm
  code/modules/wod13/datums/powers/discipline/__discipline_power.dm
  code/modules/wod13/quirks.dm
  modular_tfn/modules/auspex_auras/auspex_auras.dm
Labels: New Feature, Balance, Lore Team Approved

#686 Archetype removal
  code/__DEFINES/traits/vtm/declarations.dm
  code/__HELPERS/swinging.dm
  code/_globalvars/traits/_traits.dm
  code/_onclick/click.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/init_signals.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/wod13/gun.dm
  code/modules/spells/spell_types/shapeshift.dm
  code/modules/vtmb/archetypes.dm
  code/modules/wod13/melee.dm
  modular_tfn/modules/werewolf/werewolf_mob/transformation.dm
  tgstation.dme
Labels: Balance, Removal

#751 Shroudsight No Longer Reveals Obfuscate
  code/__DEFINES/sight.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/wod13/datums/powers/discipline/auspex.dm
Labels: Enhancement, TESTMERGE

#657 Adds Fair Glabro the Trait
  code/__DEFINES/traits/vtm/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/modules/wod13/quirks.dm
  modular_tfn/modules/werewolf/gifts.dm
  modular_tfn/modules/werewolf/werewolf_mob/life.dm
  modular_tfn/modules/werewolf/werewolf_mob/transformation.dm
Labels: New Feature, TESTMERGE, Balance, Lore Team Approved

#722 Anarch Role Expansion and Update / Triad Soldiers Removal, Rename
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/__DEFINES/jobs.dm
  code/_globalvars/contacts.dm
  code/_globalvars/lists/names.dm
  code/datums/datacore.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/antagonists/gang/gang.dm
  code/modules/jobs/jobs.dm
  code/modules/vtmb/electronics/phones/phone.dm
  code/modules/vtmb/jobs/anarchs/baron.dm
  code/modules/vtmb/jobs/anarchs/bouncer.dm
  code/modules/vtmb/jobs/anarchs/emissary.dm
  code/modules/vtmb/jobs/anarchs/liaison.dm
  code/modules/vtmb/jobs/anarchs/sweeper.dm
  code/modules/vtmb/jobs/axes.dm
  code/modules/vtmb/jobs/jobs.dm
  code/modules/vtmb/jobs/triad.dm
  code/modules/wod13/items.dmi
  code/modules/wod13/items/keys/keys.dm
  code/modules/wod13/items/stores/misc.dm
  code/modules/wod13/map.dm
  code/modules/wod13/melee.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/worn.dmi
  html/admin/banpanel.css
  modular_tfn/modules/alt_job_titles/alt_job_titles.dm
  strings/names/first_female_triad.txt
  strings/names/first_male_triad.txt
  strings/names/last_triad.txt
  tgstation.dme
Labels: Enhancement, TESTMERGE, Mapping, Icons, Lore Team Approved

#752 Adding an Obfuscate Indicator
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living_defines.dm
Labels: Enhancement, TESTMERGE

#765 Tzim Manor Improvements
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Enhancement, TESTMERGE, Mapping

#780 Adds Wristwatchs to Voivode Loadout
  code/modules/vtmb/jobs/voivode.dm
Labels: Enhancement, TESTMERGE

#788 Nat 10s Grant an Extra Success
  code/controllers/subsystem/rolling.dm
Labels: Enhancement, TESTMERGE, Balance

#790 THE ROBUST GOLD IS *BACK!* WE CAN SMOKE IT AGAIN!!!!
  code/modules/wod13/items/stores/misc.dm
Labels: Enhancement, TESTMERGE

#792 Adds robes to loadout
  modular_tfn/modules/loadout/loadout_suit.dm
Labels: Enhancement, TESTMERGE

#784 Vomit emote
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/wod13/datums/actions/dominate_commands.dm
Labels: New Feature, TESTMERGE

#778 Gun Pervert PR - Less Lethals // VERY Lethal Silver
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/wod13/ammo.dmi
  code/modules/wod13/ammostack.dm
  code/modules/wod13/items/stores/misc.dm
  code/modules/wod13/onfloor.dmi
Labels: New Feature, TESTMERGE, Balance, Icons

#798 Chinatown hotfix for doot lock IDs
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: TESTMERGE, Mapping

#759 Adds the "Unliving Hive" Quirk, letting Animalism summon bugs.
  code/__DEFINES/traits/vtm/declarations.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/vtmb/npc/beastmaster.dm
  code/modules/wod13/datums/powers/discipline/animalism.dm
  code/modules/wod13/mobs.dmi
  code/modules/wod13/npcroles.dm
  code/modules/wod13/quirks.dm
Labels: Enhancement, TESTMERGE, Balance, Lore Team Approved

#799 makes rubbershot and incap shot actually useful
  code/modules/wod13/ammostack.dm
Labels: Enhancement, TESTMERGE, Balance

#779 New Baron Weapon: Mac10
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/gridventory.dm
  code/modules/wod13/48x32weapons.dmi
  code/modules/wod13/ammo.dmi
  code/modules/wod13/guns.dm
  code/modules/wod13/lefthand.dmi
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/righthand.dmi
  code/modules/wod13/sounds/mac10.ogg
  code/modules/wod13/weapons.dmi
Labels: Enhancement, TESTMERGE, Mapping, Icons, Sounds

#787 Rebalances Kindred splat role availability
  code/modules/vtmb/jobs/doctor.dm
  code/modules/vtmb/jobs/hound.dm
  code/modules/vtmb/jobs/janitor.dm
  code/modules/vtmb/jobs/seneschal.dm
  code/modules/vtmb/jobs/sheriff.dm
  code/modules/vtmb/jobs/stripper.dm
  modular_tfn/modules/anarch_bartender/tapster_job.dm
Labels: Enhancement, TESTMERGE, Balance, Lore Team Approved

#805 Open Seal Useful
  modular_tfn/modules/werewolf/gifts.dm
Labels: TESTMERGE, Balance

#802 Removes all instances of Minstry in favor of Setite
  code/__DEFINES/tfn/vtm_defines.dm
  code/modules/vtmb/jobs/sabbatductus.dm
  code/modules/vtmb/jobs/sabbatpack.dm
  code/modules/vtmb/jobs/sabbatpriest.dm
  code/modules/vtmb/vampire_clan/setite.dm
  code/modules/wod13/datums/powers/discipline/daimonion.dm
  code/modules/wod13/items/keys/keys.dm
  strings/tips.txt
  tgstation.dme
Labels: Enhancement, TESTMERGE, Lore Team Approved

#760 Miscellaneous mapping fixes
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Enhancement, TESTMERGE, Mapping

#822 Reduces Concussions
  code/_onclick/item_attack.dm
  code/modules/wod13/datums/powers/discipline/bloodheal.dm
  code/modules/wod13/melee.dm
  modular_tfn/modules/werewolf/gifts.dm
Labels: Enhancement

#827 Diablerie flaw elaboration
  code/modules/wod13/quirks.dm
Labels: Enhancement

#804 [BOUNTY] Apocrypha XIII Eat Food Merit port
  code/datums/components/food/edible.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/reagents/chemistry/holder.dm
  modular_tfn/master_files/code/modules/vtmb/kindred_species.dm
  modular_tfn/master_files/icons/hud/screen_alert.dmi
  modular_tfn/modules/eat_food/code/eat_food_quirk.dm
  modular_tfn/modules/eat_food/code/vampirestomach.dm
  tgstation.dme
Labels: Enhancement, New Feature

#825 replacing one tile with a ladder
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Mapping

#824 Fixes Daughters of Cacophany being able to force people to say things.
  code/modules/mob/living/living_say.dm
  code/modules/wod13/datums/powers/discipline/__discipline_power.dm
  code/modules/wod13/datums/powers/discipline/melpominee.dm
Labels: Enhancement, Balance, Lore Team Approved

#814 Allows most of the Garou to choose their Sept
  code/modules/vtmb/jobs/garou/amberglade.dm
  code/modules/vtmb/jobs/garou/paintedcity.dm
Labels: Enhancement, TESTMERGE, Lore Team Approved

#800 [BOUNTY] Cooking
  _maps/map_files/Vampire/SanFrancisco.dmm
  _maps/map_files/Vampire/runtimetown.dmm
  code/__DEFINES/construction.dm
  code/__DEFINES/food.dm
  code/datums/components/crafting/recipes.dm
  code/datums/components/food/edible.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/food/pastries.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/aquarium/aquarium_behaviour.dm
  code/modules/cargo/packs.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/wod13/food.dm
  code/modules/wod13/items.dmi
  code/modules/wod13/items/stores/food.dm
  code/modules/wod13/items/stores/guns.dm
  code/modules/wod13/map.dm
  code/modules/wod13/onfloor.dmi
  modular_tfn/modules/alt_job_titles/outfits.dm
  modular_tfn/modules/food/code/drinks.dm
  modular_tfn/modules/food/code/food.dm
  modular_tfn/modules/food/code/recipes.dm
  modular_tfn/modules/food/code/structure.dm
  modular_tfn/modules/food/icons/food_onfloor.dmi
  modular_tfn/modules/food/icons/items.dmi
  tgstation.dme
  tools/UpdatePaths/Scripts/TFN Scripts/582_wirecutters.txt
  tools/UpdatePaths/Scripts/TFN Scripts/800_food.txt
Labels: Enhancement, Refactor, TESTMERGE

#849 Fixes Pancake Stacking
  code/game/objects/items/food/pastries.dm
Labels: Enhancement

#564 Remakes the Theurge's "Sense Wyrm" gift.
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/tfn/vtm_defines.dm
  code/datums/hud.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/living_defines.dm
  code/modules/wod13/datums/powers/discipline/auspex.dm
  code/modules/wod13/npc.dm
  code/modules/wod13/onyxcombat/misc.dm
  code/modules/wod13/onyxcombat/rage.dm
  modular_tfn/modules/auspex_auras/auspex_auras.dm
  modular_tfn/modules/werewolf/gifts.dm
  modular_tfn/modules/werewolf/werewolf_mob/werewolf.dm
  modular_tfn/modules/wyrm_taint_aura/Wyrm_taint_auras.dm
  tgstation.dme
Labels: Enhancement, TESTMERGE, Balance, Lore Team Approved

#839 fixes slim fem variants for the police longsleeve and utility uniform
  code/modules/wod13/worn_slim_f.dmi
Labels: Enhancement, TESTMERGE, Icons

#847 Making Illegal Identity a Flaw
  code/modules/wod13/quirks.dm
Labels: TESTMERGE, Balance

#848 Fixes accessing .45 from the dealer
  code/modules/wod13/cargo.dm
Labels: TESTMERGE, Balance

#844 Kinfolk merit
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/traits/vtm/declarations.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/wod13/quirks.dm
  modular_tfn/modules/werewolf/glyphs.dm
Labels: Enhancement, TESTMERGE

#832 Adds Seven Funny Lil' Languages to the merits
  code/modules/surgery/organs/tongue.dm
  code/modules/wod13/quirks.dm
  icons/misc/language.dmi
  modular_tfn/modules/language/armenian.dm
  modular_tfn/modules/language/farsi.dm
  modular_tfn/modules/language/irish.dm
  modular_tfn/modules/language/korean.dm
  modular_tfn/modules/language/scottish.dm
  modular_tfn/modules/language/tagalog.dm
  modular_tfn/modules/language/welsh.dm
  tgstation.dme
Labels: Enhancement, TESTMERGE, Icons

#781 Jazz Club Remap... Again?!
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/instruments/stationary.dm
  code/modules/wod13/items/keys/keys.dm
  icons/obj/musician.dmi
Labels: TESTMERGE, Mapping

#856 Lets Ginger Hispo lay down
  code/modules/wod13/hispo.dmi
Labels: TESTMERGE, Icons

#865 removes Capp from Capo
  code/modules/vtmb/jobs/giovanni.dm
Labels: Enhancement, TESTMERGE, Lore Team Approved
