Repository The-Final-Nights/The-Final-Nights, pull requests merged in 2025-04, with the labels that each got.

#201 Fixes unpowered radios still receiving
  code/modules/vtmb/electronics/p25.dm
Labels: Enhancement

#101 Update Balefire
  code/modules/spells/spell_types/aimed.dm
  code/modules/wod13/datums/powers/discipline/daimonion.dm
Labels: Enhancement, Testing Evidence Required

#139 Baal's Caress Weapons Cannot Be Shared/Stolen
  code/modules/wod13/datums/powers/discipline/quietus.dm
  code/modules/wod13/melee.dm
Labels: Enhancement, Changes Requested, Testing Evidence Required

#178 Adds a few more items to clothing stores
  code/modules/wod13/items/stores/clothes.dm
Labels: Enhancement

#83 Scrub Sprites
  code/modules/wod13/clothing.dmi
  code/modules/wod13/items/clothes/under.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: New Feature

#114 Necromancy Ghost Sight is Free Like Auspex Now
  code/modules/wod13/datums/powers/discipline/necromancy.dm
Labels: Enhancement, Balance

#194 .50 Deagle and .50 Sniper Hotfix
  code/modules/wod13/cargo.dm
  code/modules/wod13/guns.dm
  tgstation.dme
Labels: Enhancement, Balance

#158 Adds Claimable Apartments
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/wod13/ambient.dm
  code/modules/wod13/items/keys/keys.dm
  code/modules/wod13/structures/doors/vampdoor.dm
  code/modules/wod13/tiles.dmi
Labels: New Feature, Mapping

#187 Cappadocian Crypt Haven
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/vampire_clane/cappadocian.dm
  code/modules/wod13/ambient.dm
  code/modules/wod13/items/keys/keys.dm
  code/modules/wod13/structures/doors/vampdoor_wood.dm
Labels: Enhancement, Mapping

#192 Subtle emotes now show the speech indicator when you're typing
  code/modules/mob/living/emote.dm
  code/modules/mob/mob_say.dm
  modular_tfn/modules/subtle/subtle.dm
Labels: Enhancement, TESTMERGE, Testing Evidence Required

#49 Adds a cosmetic fleshcrafting surgery
  code/modules/vtmb/surgery/fleshcraft.dm
  code/modules/vtmb/surgery/fleshcraft/cosmetic_fleshcrafting.dm
  tgstation.dme
Labels: New Feature, TESTMERGE

#245 Removes a buggy proc rellated to item lists
  code/modules/wod13/onyxcombat.dm
Labels: Enhancement, Removal

#234 adds nun robes (SPRITE CHANGES PLEASE CHECK FOR CONFLICTS)
  code/modules/wod13/clothing.dmi
  code/modules/wod13/items/clothes/head.dm
  code/modules/wod13/items/clothes/suit.dm
  code/modules/wod13/items/stores/clothes.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: New Feature, TESTMERGE, Icons

#230 Projectiles pull you out of Obfuscate
  code/modules/wod13/datums/powers/discipline/obfuscate.dm
Labels: Enhancement, Balance

#226 Adapt DONOS from Nearweb: OVERWATCH
  code/__DEFINES/time.dm
  code/__HELPERS/chat.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/overwatch.dm
  code/datums/http.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/client/preferences.dm
  code/modules/vtmb/kindred_species.dm
  config/config.txt
  tgstation.dme
Labels: New Feature, Testing Evidence Required, Administration

#244 Adds hijab to the clothes store
  code/modules/wod13/items/stores/clothes.dm
Labels: Enhancement

#252 SFPD - Unmarked Cars
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/wod13/car.dm
  code/modules/wod13/cars.dmi
Labels: New Feature, Balance

#199 Quick Dualwield Pass
  code/modules/wod13/guns.dm
Labels: Enhancement, Balance

#250 MEAT MATRIX CONTENT (PART ONE!)
  code/game/objects/items/plushes.dm
  code/modules/mining/equipment/regenerative_core.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/vtmb/magic/pyramid.dm
  code/modules/vtmb/vampire_clane/tzimisce.dm
  code/modules/wod13/48x32weapons.dmi
  code/modules/wod13/datums/powers/discipline/vicissitude.dm
  code/modules/wod13/icons.dmi
  code/modules/wod13/items.dmi
  code/modules/wod13/lefthand.dmi
  code/modules/wod13/melee.dm
  code/modules/wod13/mobs.dmi
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/props.dmi
  code/modules/wod13/righthand.dmi
  code/modules/wod13/sounds/femurbreaker.ogg
  code/modules/wod13/weapons.dmi
  icons/obj/surgery.dmi
Labels: New Feature, Changes Requested, Balance, Icons

#256 Lets you wear the Cross (Id/Hunter) on your neck OR as an ID slot.
  code/modules/vtmb/jobs/jobs.dm
Labels: Enhancement

#261 Physique Affects Human Health (HOTFIX)
  code/modules/client/preferences.dm
Labels: Enhancement, Balance

#268 SFPD - Adds a belt to the SFPD uniform
  code/modules/wod13/worn.dmi
Labels: Enhancement, Icons

#276 SOUND - New shutter sounds from shiptest (who got them from skyrat)
  code/game/machinery/doors/poddoor.dm
  sound/machines/shutters_close.ogg
  sound/machines/shutters_open.ogg
Labels: Documentation, Sounds

#185 Melee Multipliers on Simples/Carbons/Objects and Physique Melee Rebalance
  code/_onclick/item_attack.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Enhancement, Balance

#151 CoG/Bone Gnawer Umbra Portals
  _maps/map_files/Mining/Lavaland.dmm
Labels: Enhancement, TESTMERGE, Mapping

#267 SFPD - Improves the lightbar on the unmarked unit
  code/modules/wod13/cars.dmi
Labels: Enhancement, Icons

#259 Changes the jobs Tzimisce can do
  code/modules/vtmb/jobs/hound.dm
  code/modules/vtmb/jobs/prince.dm
  code/modules/vtmb/jobs/seneschal.dm
Labels: Enhancement, Balance

#255 Garou Transformation Refactor: The Weakrefening
  code/__DEFINES/time.dm
  code/_onclick/hud/werewolf.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/werewolf/transformation.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/vtmb/werewolf/auspice.dm
  code/modules/vtmb/werewolf/gifts.dm
  code/modules/vtmb/werewolf_species.dm
Labels: Enhancement, Refactor, TESTMERGE

#275 Examine panel expansion & NSFW content pref
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/examine_tgui.dm
  modular_tfn/code/modules/mob/living/carbon/human/human_defines.dm
  tgui/packages/tgui/interfaces/ExaminePanel.tsx
Labels: Enhancement, Refactor

#279 Fixes Prince Announcement not appearing when a prince arrives.
  code/modules/vtmb/jobs/prince.dm
Labels: Enhancement

#134 Converts XP to be client wide, instead of character wide.
  code/game/objects/items/defib.dm
  code/game/objects/items/mop.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living_say.dm
  code/modules/vehicles/pimpin_ride.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/wod13/graveyard.dm
Labels: Enhancement, Balance

#272 SFPD - Department remodel
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/game/objects/structures/railings.dm
  code/modules/wod13/npcroles.dm
  icons/obj/railings.dmi
Labels: Enhancement, TESTMERGE, Merge Conflict, Mapping

#262 Emote Update Part 2
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/emote.dm
  sound/mobs/humanoids/human/blink/blink.ogg
  sound/mobs/humanoids/human/blink/blinkrapid.ogg
  sound/mobs/humanoids/human/giggle/female_giggle_1.ogg
  sound/mobs/humanoids/human/giggle/female_giggle_2.ogg
  sound/mobs/humanoids/human/giggle/male_giggle_1.ogg
  sound/mobs/humanoids/human/giggle/male_giggle_2.ogg
  sound/mobs/humanoids/human/giggle/male_giggle_3.ogg
Labels: Enhancement

#89 Eyes of the Beast and Feral Claws are Closer to their Tabletop Equivalents - Test Results Included - Shadow Tentacles also Affected Incidentally
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/wod13/datums/powers/discipline/obtenebration.dm
  code/modules/wod13/datums/powers/discipline/protean.dm
  code/modules/wod13/melee.dm
Labels: Enhancement, Balance

#260 Rename the Baali Keys to make it less meta
  code/modules/wod13/items/keys/keys.dm
Labels: Enhancement, Balance

#265 makes broken tzimisce floor uncraftable (BUGFIX)
  code/modules/wod13/datums/powers/discipline/vicissitude.dm
Labels: Enhancement, Removal

#271 Makes madness speech cd 5 seconds.
  code/modules/vtmb/vampire_clane/malkavian.dm
Labels: Enhancement, Balance

#281 Kuei-Jin Awaken out of Crit Fix
  code/modules/vtmb/kuei_jin.dm
Labels: Enhancement, Balance

#285 Minimum Generation in Savefile [HOTFIX]
  code/modules/client/preferences_savefile.dm
Labels: Enhancement, Balance

#298 Properly fixes %d not writing the correct in universe date on paper forms.
  code/__DEFINES/time.dm
  code/modules/paperwork/paper.dm
Labels: Enhancement

#299 Jukebox sounds refactor + More admin shenanigens with sounds!
  code/__DEFINES/_misc.dm
  code/__DEFINES/admin.dm
  code/__DEFINES/chat.dm
  code/__DEFINES/colors.dm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/instruments.dm
  code/__DEFINES/song.dm
  code/__HELPERS/atoms.dm
  code/__HELPERS/roundend.dm
  code/__HELPERS/unsorted.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/processing/instruments.dm
  code/controllers/subsystem/ticker.dm
  code/datums/components/connect_range.dm
  code/datums/components/jukebox.dm
  code/game/machinery/dance_machine.dm
  code/game/objects/items/dualsaber.dm
  code/game/sound.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/playsound.dm
  code/modules/admin/verbs/request_internet_sound.dm
  code/modules/instruments/items.dm
  code/modules/instruments/songs/_song.dm
  code/modules/instruments/songs/editor.dm
  code/modules/instruments/songs/play_synthesized.dm
  code/modules/mob/mob_helpers.dm
  code/modules/requests/request.dm
  code/modules/requests/request_manager.dm
  code/modules/wod13/npcroles.dm
  config/config.txt
  config/game_options.txt
  config/reboot_themes/cain.ogg
  config/reboot_themes/die.ogg
  config/reboot_themes/malkavian.ogg
  tgstation.dme
  tgui/packages/tgui/interfaces/InstrumentEditor.tsx
  tgui/packages/tgui/interfaces/Jukebox.tsx
  tgui/packages/tgui/styles/interfaces/RequestManager.scss
  tools/midi2piano/MidiDependencies/__init__.py
  tools/midi2piano/MidiDependencies/midi.py
  tools/midi2piano/README.txt
  tools/midi2piano/easygui/__init__.py
  tools/midi2piano/midi/__init__.py
  tools/midi2piano/midi2piano.py
  tools/midi2piano/pyperclip/__init__.py
  tools/midi2piano/pyperclip/clipboards.py
  tools/midi2piano/pyperclip/exceptions.py
  tools/midi2piano/pyperclip/windows.py
Labels: Enhancement, Refactor, Administration, Sounds, Config

#315 No More KJ/Garou Catgirls
  code/modules/vtmb/kuei_jin.dm
  code/modules/vtmb/werewolf_species.dm
Labels: Removal

#304 Ports Pixelshifting to the game!
  code/__DEFINES/keybinding.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/mob_movement.dm
  code/modules/pixel_shift/code/pixel_shift.dm
  code/modules/pixel_shift/readme.md
  tgstation.dme
Labels: Documentation, New Feature

#296 Bagged and tagged
  code/modules/wod13/clothing.dmi
  code/modules/wod13/items/clothes/head.dm
  code/modules/wod13/items/stores/misc.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: New Feature, TESTMERGE, Balance

#292 [READY FOR MERGE] Raises Vampire Final Death Threshold, AHeal Fixes Torpor, Brain Damage Changes
  code/__DEFINES/combat.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/vtmb/kuei_jin.dm
  code/modules/vtmb/werewolf/gifts.dm
  code/modules/wod13/datums/powers/discipline/bloodheal.dm
  code/modules/wod13/onyxcombat.dm
Labels: Enhancement, Balance, Administration

#291 TGUI admin panel & adds mentors and mentor panel, Attempt 2
  code/__DEFINES/admin.dm
  code/__DEFINES/chat.dm
  code/__DEFINES/mentor.dm
  code/__DEFINES/span.dm
  code/__DEFINES/stat_panel.dm
  code/__DEFINES/text.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/logging/admin.dm
  code/__HELPERS/text.dm
  code/modules/admin/admin_follow.dm
  code/modules/admin/admin_more_info.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/chat_commands.dm
  code/modules/admin/holder2.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/sql_message_system.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/_help.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/mentorhelp.dm
  code/modules/admin/verbs/mentors_edit.dm
  code/modules/admin/verbs/ticket_embeds.dm
  code/modules/admin/verbs/ticket_helpers.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/who.dm
  code/modules/mentor/config.dm
  code/modules/mentor/mentor.dm
  code/modules/mentor/mentor_admintools.dm
  code/modules/mentor/mentor_loading.dm
  code/modules/mentor/mentor_verbs.dm
  code/modules/mentor/mentorpm.dm
  code/modules/mentor/mentorsay.dm
  code/modules/tgui/states/mentor.dm
  code/modules/tgui/states/never.dm
  config/config.txt
  tgstation.dme
  tgui/packages/tgui-panel/chat/constants.ts
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
  tgui/packages/tgui/interfaces/TicketBrowser.jsx
  tgui/packages/tgui/interfaces/TicketMessenger.jsx
Labels: Enhancement, Refactor, Administration

#314 Increases Spraycan Capacity
  code/game/objects/items/crayons.dm
Labels: Enhancement, Balance

#301 update debug server to v2.3.5
  debug_server.dll
Labels: Enhancement, Development

#289 I AM IN YOUR WALLS (auspex 4 telepathy but epic)
  code/modules/wod13/datums/powers/discipline/auspex.dm
Labels: Enhancement, TESTMERGE, Balance

#318 [HOTFIX] Fixes some song stuff
  code/__DEFINES/song.dm
  code/game/machinery/dance_machine.dm
Labels: Enhancement

#242 Assorted Vicissitude/Tzimisce Fluff Changes + Some De-Cluttering of Tzimisce clan file
  code/modules/vtmb/vampire_clane/lasombra.dm
  code/modules/vtmb/vampire_clane/tzimisce.dm
  code/modules/wod13/datums/powers/discipline/protean.dm
  code/modules/wod13/datums/powers/discipline/vicissitude.dm
  code/modules/wod13/guns.dm
  code/modules/wod13/items.dmi
  code/modules/wod13/lefthand.dmi
  code/modules/wod13/melee.dm
  code/modules/wod13/righthand.dmi
  icons/obj/device.dmi
  icons/obj/surgery.dmi
Labels: Enhancement, Refactor, TESTMERGE, Icons

#270 Dominate and Presence now operate on probabilities
  code/__DEFINES/span.dm
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/wod13/datums/powers/discipline/dementation.dm
  code/modules/wod13/datums/powers/discipline/dominate.dm
  code/modules/wod13/datums/powers/discipline/presence.dm
Labels: Enhancement, TESTMERGE, Balance

#317 TheaterExpandedRemap
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: TESTMERGE, Mapping

#345 Character Notes: The Fixening
  code/modules/client/preferences_savefile.dm
Labels: Enhancement

#344 Fixes "Potent Blood" being broken for anyone latejoining
  code/modules/vtmb/_signals.dm
  code/modules/wod13/quirks.dm
Labels: Enhancement

#354 makes our code compile again
  code/modules/wod13/datums/powers/discipline/dementation.dm
Labels: Enhancement, FUCK

#303 Re-potence
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/wod13/datums/powers/discipline/potence.dm
Labels: Enhancement, TESTMERGE, Balance

#286 Thaumaturgy buff and rework
  code/modules/projectiles/projectile.dm
  code/modules/vtmb/artifacts.dm
  code/modules/wod13/datums/powers/discipline/thaumaturgy.dm
Labels: Enhancement, TESTMERGE, Balance

#282 Re-Enables Diablerie, Fixes Burn Healing On Feeding
  code/__DEFINES/wod13/status_effects_debuffs.dm
  code/modules/wod13/bloodsucking.dm
  code/modules/wod13/status_effects/debuffs.dm
Labels: Enhancement, TESTMERGE, Balance

#306 Gargoyle Enrichening
  code/__DEFINES/traits/declarations.dm
  code/datums/elements/caltrop.dm
  code/modules/vtmb/vampire_clane/gargoyle.dm
  code/modules/wod13/icons.dmi
  code/modules/wod13/quirks.dm
Labels: Enhancement, New Feature, Icons

#288 Re-adds toggle fullscreen
  code/datums/keybinding/client.dm
  code/modules/client/verbs/ooc.dm
  interface/skin.dmf
Labels: Enhancement

#357 Adds the Organovore Flaw
  code/__DEFINES/food.dm
  code/__DEFINES/tfn/vtm_defines.dm
  code/__DEFINES/traits/declarations.dm
  code/datums/components/food/edible.dm
  code/game/objects/items/food/meat.dm
  code/modules/surgery/organs/organ_internal.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/wod13/bloodsucking.dm
  code/modules/wod13/quirks.dm
Labels: New Feature, Changes Requested

#311 Fixes command job eager selection
  code/controllers/subsystem/job.dm
Labels: Enhancement, Stale

#316 Implements minimum character age restriction for jobs
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/vtmb/jobs/anarchs/baron.dm
  code/modules/vtmb/jobs/giovanni.dm
  code/modules/vtmb/jobs/primogen.dm
  code/modules/vtmb/jobs/prince.dm
  code/modules/vtmb/jobs/regent.dm
  code/modules/vtmb/jobs/sheriff.dm
  code/modules/vtmb/jobs/voivode.dm
Labels: Enhancement

#323 Re-adds the late party timer if the player is dead or in the lobby
  code/modules/mob/dead/dead.dm
Labels: Enhancement
