Repository The-Final-Nights/The-Final-Nights, pull requests merged in 2025-08, with the labels that each got.

#655 Adds swag shoes and high boots to loadout
  modular_tfn/modules/loadout/loadout_footwear.dm
Labels: Enhancement

#664 The Bullfighter & Rebellion...again.
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/wod13/guns.dm
Labels: Enhancement

#668 Fixes TGUI menu not focusing on creation
  code/__DEFINES/speech_channels.dm
  code/datums/ai/hauntium/haunted_controller.dm
  code/datums/keybinding/communication.dm
  code/game/objects/effects/wanted_poster.dm
  code/modules/mob/mob_say.dm
  tgui/packages/tgui-say/515/TguiSay.tsx
  tgui/packages/tgui-say/515/constants.ts
  tgui/packages/tgui-say/515/helpers.ts
  tgui/packages/tgui-say/515/styles/button.scss
  tgui/packages/tgui-say/515/styles/content.scss
  tgui/packages/tgui-say/515/styles/dragzone.scss
  tgui/packages/tgui-say/515/styles/main.scss
  tgui/packages/tgui-say/515/styles/textarea.scss
  tgui/packages/tgui-say/515/styles/window.scss
  tgui/packages/tgui-say/516/TguiSay.tsx
  tgui/packages/tgui-say/516/constants.ts
  tgui/packages/tgui-say/516/helpers.ts
  tgui/packages/tgui-say/516/styles/colors.scss
  tgui/packages/tgui-say/ChannelIterator.ts
  tgui/packages/tgui-say/TguiSay.tsx
  tgui/packages/tgui-say/constants.ts
  tgui/packages/tgui-say/helpers.ts
  tgui/packages/tgui-say/index.tsx
  tgui/packages/tgui-say/styles/colors.scss
  tgui/packages/tgui-say/styles/main.scss
  tgui/packages/tgui-say/styles/styles.scss
Labels: Enhancement, Refactor

#656 minor oakland fix
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Enhancement, Mapping

#670 .45 for $2,100? What a steal!
  code/modules/wod13/cargo.dm
  code/modules/wod13/items/stores/guns.dm
Labels: Enhancement, Balance

#674 Fix Flesh and Giant Combo Wombo
  code/modules/vtmb/chi_disciplines.dm
Labels: Enhancement, Balance

#676 Flame and Blood Katana adjustment
  code/modules/wod13/melee.dm
Labels: Enhancement, Balance

#679 Garou hp fix
  modular_tfn/modules/werewolf/werewolf_mob/werewolf.dm
Labels: Enhancement, Balance

#658 BSD Pit Mini-Changes
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Enhancement, Mapping

#641 Canonizes Thaumaturgy abilities
  code/__DEFINES/traits/vtm/declarations.dm
  code/__DEFINES/traits/vtm/sources.dm
  code/__DEFINES/wod13/discipline.dm
  code/__HELPERS/atoms.dm
  code/controllers/subsystem/rolling.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/modules/mob/living/living_defines.dm
  code/modules/vtmb/jobs/hunter.dm
  code/modules/vtmb/jobs/national_guard.dm
  code/modules/vtmb/jobs/swat.dm
  code/modules/vtmb/magic/pyramid.dm
  code/modules/wod13/bloodsucking.dm
  code/modules/wod13/datums/powers/discipline/__discipline_power.dm
  code/modules/wod13/datums/powers/discipline/thaumaturgy.dm
  code/modules/wod13/datums/powers/discipline/thaumaturgy/path_of_blood.dm
  code/modules/wod13/items.dmi
  modular_tfn/modules/magic/code/_ritual.dm
  modular_tfn/modules/magic/code/thaumaturgy/arcane_tome.dm
  modular_tfn/modules/magic/code/thaumaturgy/blood_of_potency_effect.dm
  modular_tfn/modules/magic/code/thaumaturgy/blood_rage_effect.dm
  modular_tfn/modules/magic/code/thaumaturgy/rune_drawing.dm
  modular_tfn/modules/magic/icons/arcane_tome.dmi
  modular_tfn/modules/vitae/code/embracing.dm
  tgstation.dme
Labels: Enhancement, New Feature, Balance, Lore Team Approved

#651 Hopefully fixes garou renown behavior
  code/modules/client/preferences.dm
Labels: Enhancement

#660 Cuts NPC Dialogue
  code/modules/wod13/npc.dm
Labels: Enhancement, TESTMERGE

#683 Ports - Rebalances some sizes on containers (#22)
  code/datums/components/storage/concrete/_concrete.dm
  code/datums/components/storage/storage.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/sixpack.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/items/storage/wallets.dm
  code/modules/vtmb/gridventory.dm
Labels: Enhancement, Balance

#673 guns the mag-ening
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Enhancement, Mapping

#669 Cappadocian/Kiasyd/Gargoyle/Nosferatu bodymodel invisibility fix
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/wod13/datums/powers/discipline/vicissitude.dm
Labels: Enhancement, FUCK

#682 Dominate Case Sensitivity Coldfix
  code/modules/wod13/datums/powers/discipline/dominate.dm
Labels: Enhancement

#689 Giovanni manion expansion
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Enhancement, Mapping

#697 Misc Fixes
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Mapping

#688 Fixes Slapping Tables
  code/_onclick/item_attack.dm
Labels: Enhancement

#677 Endron Ghoulification (Executive and Security Agent can be Ghouls now)
  code/modules/vtmb/jobs/garou/poisonshore.dm
Labels: Enhancement, Balance

#703 Updating Prince to the 7 Clans of the Camarilla
  code/modules/vtmb/jobs/prince.dm
Labels: Enhancement, Balance, Administration

#681 Small Gargoyle QOL Fixes
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/vtmb/vampire_clan/gargoyle.dm
  code/modules/wod13/datums/powers/discipline/visceratika.dm
Labels: Enhancement, Balance, Lore Team Approved

#706 Give Wyrm Tainted Corax have EVIL TAINTED FORM!!!
  code/modules/wod13/corax_corvid.dmi
  code/modules/wod13/corax_crinos.dmi
  modular_tfn/modules/werewolf/werewolf_mob/lupus.dm
  modular_tfn/modules/werewolf/werewolf_mob/werewolf_update_icons.dm
Labels: New Feature, Icons

#721 Removing the Man Moans
  code/modules/wod13/items/narcotics/bong.dm
  code/modules/wod13/sounds/lungbust_moan1.ogg
  code/modules/wod13/sounds/lungbust_moan2.ogg
  code/modules/wod13/sounds/lungbust_moan3.ogg
Labels: Removal

#707 Made Hungry Dead's Masquerade to be less Anglophobic
  code/modules/vtmb/kuei_jin.dm
Labels: Enhancement

#712 Literally 1984
  code/modules/admin/admin_verbs.dm
  modular_tfn/modules/redaction/code/admin.dm
  modular_tfn/modules/redaction/code/speech.dm
  modular_tfn/modules/redaction/code/subsystem/redaction.dm
  modular_tfn/modules/redaction/readme.md
  tgstation.dme
Labels: New Feature, TESTMERGE, Administration

#726 Fixes Typhon's Brew
  code/datums/components/crafting/recipes.dm
Labels: Enhancement

#699 Cammie Improvements Revival, Revived
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Enhancement, TESTMERGE, Balance, Mapping

#730 Fixes map runtimes with ropes
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Enhancement, TESTMERGE, Mapping

#734 TGUI runtime fixes
  code/controllers/subsystem/tgui.dm
  interface/interface.dm
Labels: Enhancement, TESTMERGE

#737 Adds a "Lower Path" Button
  code/modules/client/preferences.dm
Labels: New Feature, TESTMERGE

#740 Potence Tackles Viable
  code/modules/wod13/datums/powers/discipline/potence.dm
Labels: Enhancement, TESTMERGE, Balance

#727 Celerity now gives Scaling Dex, Revived
  code/modules/wod13/datums/powers/discipline/celerity.dm
Labels: Enhancement, TESTMERGE, Balance

#728 Making torpor timers static
  code/modules/mob/living/status_procs.dm
Labels: Enhancement, Balance, Lore Team Approved

#725 Commenting out select Arcade Rewards
  code/game/machinery/computer/arcade.dm
Labels: Removal

#708 Gives the Primogens + Regent P25s.
  code/modules/vtmb/jobs/primogen.dm
  code/modules/vtmb/jobs/regent.dm
Labels: Enhancement, TESTMERGE, Balance

#744 Adds an Anarch Bartender/Server role for Humans and Ghouls.
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/__DEFINES/jobs.dm
  code/modules/jobs/jobs.dm
  code/modules/wod13/items/keys/keys.dm
  modular_tfn/modules/alt_job_titles/alt_job_titles.dm
  modular_tfn/modules/anarch_bartender/tapster.dmi
  modular_tfn/modules/anarch_bartender/tapster_job.dm
  modular_tfn/modules/anarch_bartender/tapster_objects.dm
  tgstation.dme
Labels: Enhancement, TESTMERGE, Mapping

#746 lemme get uhhhh boneless pizz-i mean tzimisce
  code/modules/wod13/datums/powers/discipline/vicissitude.dm
Labels: TESTMERGE, Balance

#735 Band aid fix for character preview sheet stretching
  code/modules/vtmb/vampire_clan/kiasyd.dm
Labels: Enhancement

#733 Fixes phone contacts (finally)
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/_globalvars/contacts.dm
  code/modules/vtmb/electronics/computers/computer.dm
  code/modules/vtmb/electronics/phones/phone.dm
Labels: Enhancement, Refactor, TESTMERGE, Mapping

#755 The Community Center (Totally Not An Evil Fucked Up Place Guys)
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/vampire_clan/ministry.dm
  code/modules/wod13/decor.dm
  code/modules/wod13/items/keys/keys.dm
  code/modules/wod13/props.dmi
  sound/wod13/pilotlight.ogg
Labels: Mapping, Icons

#763 [MAINTAINERS BEWARE] [REVIEW AT OWN PERIL] [DANGEROUSLY HUGE PR] [INSANITY AHEAD] Fixes two tiles.
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Mapping

#758 Paper runtime fix
  code/modules/paperwork/paper.dm
Labels: Enhancement

#767 removes mcluskys
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Balance, Mapping

#729 Taxi spawning in the metro fix
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/controllers/subsystem/job.dm
  code/modules/mob/mob_defines.dm
  code/modules/vtmb/jobs/taxi.dm
Labels: Enhancement, Changes Requested, Mapping

#762 Added Deaf and Blind Trait (More like Re-Enable Them)
  code/datums/quirks/negative.dm
Labels: Enhancement, TESTMERGE
