Repository The-Final-Nights/The-Final-Nights, pull requests merged in 2025-03, with the labels that each got.

#3 thanks flav - removes weird code
  code/__DEFINES/mobs.dm
  code/__HELPERS/mobs.dm
Labels: enhancement

#4 Dumbs down torpor timers
  code/modules/mob/living/status_procs.dm
Labels: enhancement

#10 a very simple fix to fortitude.
  code/modules/vtmb/disciplines.dm
Labels: enhancement

#33 Weakrefs QoL update
  code/__DEFINES/vv.dm
  code/datums/weakrefs.dm
Labels: documentation, enhancement

#50 Fix Setite curse.
  code/modules/vtmb/vampire_clane/ministry.dm
Labels: enhancement, refactor

#56 Discipline Buffs And Changes
  code/__DEFINES/wod13/discipline.dm
  code/modules/wod13/datums/powers/discipline/__discipline_power.dm
  code/modules/wod13/datums/powers/discipline/auspex.dm
  code/modules/wod13/datums/powers/discipline/bloodheal.dm
  code/modules/wod13/datums/powers/discipline/celerity.dm
  code/modules/wod13/datums/powers/discipline/fortitude.dm
  code/modules/wod13/datums/powers/discipline/obfuscate.dm
  code/modules/wod13/datums/powers/discipline/potence.dm
  code/modules/wod13/datums/powers/discipline/visceratika.dm
Labels: enhancement, refactor

#70 Trusted player whitelist
  code/__DEFINES/jobs.dm
  code/__DEFINES/tfn/vtm_defines.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/whitelists.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/vtmb/jobs/fbi.dm
Labels: enhancement

#11 completely slashes damage values
  code/modules/wod13/ammostack.dm
  code/modules/wod13/melee.dm
Labels: enhancement

#57 Small Discipline Buffs and Changes
  code/modules/wod13/datums/powers/discipline/__discipline_power.dm
  code/modules/wod13/datums/powers/discipline/healer_valeren.dm
  code/modules/wod13/datums/powers/discipline/melpominee.dm
  code/modules/wod13/datums/powers/discipline/mytherceria.dm
  code/modules/wod13/datums/powers/discipline/presence.dm
  code/modules/wod13/datums/powers/discipline/quietus.dm
  code/modules/wod13/datums/powers/discipline/serpentis.dm
Labels: enhancement, refactor

#125 slight refactor to madness speech
  code/game/objects/items/devices/chameleonproj.dm
  code/modules/vtmb/vampire_clane/malkavian.dm
Labels: TESTMERGE

#55 Small Garou nerfs + the best thing since sliced bread
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/werewolf/damage_procs.dm
  code/modules/mob/living/carbon/werewolf/lupus.dm
  code/modules/mob/living/carbon/werewolf/werewolf.dm
  code/modules/mob/living/carbon/werewolf/werewolf_defense.dm
Labels: TESTMERGE

#128 Refactors our dice rolling system
  code/__DEFINES/_helpers.dm
  code/controllers/subsystem/rolling.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/vtmb/chi_disciplines.dm
  code/modules/vtmb/frenzy.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/wod13/ammostack.dm
  code/modules/wod13/datums/powers/discipline/melpominee.dm
  code/modules/wod13/effects/vip_barrier.dm
  code/modules/wod13/procs.dm
  code/modules/wod13/structures/hydroponics.dm
  code/modules/wod13/verbs/dice.dm
  tgstation.dme
Labels: refactor, TESTMERGE

#94 Revert "Finally gives people bloodheal 2 and 3"
  code/modules/vtmb/kindred_species.dm
Labels: TESTMERGE

#75 More Baron Bloodlines
  code/modules/vtmb/jobs/anarchs/baron.dm
Labels: enhancement

#147 Remove unnecessary maps
  _maps/deltastation.json
  _maps/icebox.json
  _maps/kilostation.json
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Below.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Vampire-Detroit/Detroit.dmm
  _maps/map_files/Vampire/KindredCity.dmm
  _maps/map_files/Vampire/KindredCity2 — копия.dmm
  _maps/map_files/Vampire/ochko_uzhasa.dmm
  _maps/metastation.json
  code/datums/map_config.dm
  config/maps.txt
Labels: Mapping, Removal

#149 fix Armor of Terra immortality
  code/modules/wod13/datums/powers/discipline/visceratika.dm
Labels: Enhancement, Balance, FUCK

#103 Add Warehouse Items
  code/modules/wod13/cargo.dm
Labels: New Feature, TESTMERGE

#88 Morality System - Foundation
  code/__DEFINES/tfn/vtm_defines.dm
  code/__HELPERS/global_lists.dm
  code/_onclick/hud/alert.dm
  code/game/objects/items/defib.dm
  code/game/objects/structures/morgue.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/status_procs.dm
  code/modules/vtmb/frenzy.dm
  code/modules/vtmb/ghoul_species.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/vtmb/vampire_clane/baali.dm
  code/modules/vtmb/vampire_clane/clane.dm
  code/modules/vtmb/vampire_clane/doc.dm
  code/modules/vtmb/vampire_clane/lasombra.dm
  code/modules/vtmb/vampire_clane/old_clan_tzimisce.dm
  code/modules/vtmb/vampire_clane/salubri.dm
  code/modules/vtmb/vampire_clane/true_brujah.dm
  code/modules/vtmb/vampire_clane/tzimisce.dm
  code/modules/wod13/bloodsucking.dm
  code/modules/wod13/car.dm
  code/modules/wod13/datums/powers/discipline/healer_valeren.dm
  code/modules/wod13/decor.dm
  code/modules/wod13/items/quran.dm
  code/modules/wod13/lombard.dm
  code/modules/wod13/npc_movement.dm
  code/modules/wod13/procs.dm
  code/modules/wod13/quirks.dm
  modular_tfn/modules/morality/morality.dm
  modular_tfn/modules/morality/morality_component.dm
  tgstation.dme
Labels: Enhancement, Refactor, New Feature, TESTMERGE, Testing Evidence Required

#116 Early-VentrueRework: THIS MAP DEPENDS ON PR #111
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Enhancement, Testing Evidence Required, Mapping

#157 Movement Fixes
  code/modules/wod13/npc.dm
  code/modules/wod13/onyxcombat.dm
Labels: Enhancement, Balance

#169 [Port] Adds leaning from the upstream
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits.dm
  code/_onclick/drag_drop.dm
  code/datums/components/leanable.dm
  code/datums/elements/climbable.dm
  code/datums/status_effects/neutral.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/structures/railings.dm
  code/game/objects/structures/window.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/wod13/decor.dm
  code/modules/wod13/npc.dm
  code/modules/wod13/structures/doors/vampdoor.dm
  code/modules/wod13/wallcode.dm
  tgstation.dme
Labels: Enhancement, New Feature, Balance

#167 Badge sprite fix + dead pixel removal
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: Enhancement, Icons

#164 Makes Lasombra weakness less crippling, applies it properly to radios.
  code/modules/vtmb/electronics/p25.dm
  code/modules/vtmb/electronics/phones/phone.dm
  code/modules/vtmb/electronics/phones/phone_voice.dm
Labels: Enhancement, Testing Evidence Required, Balance

#163 Voice of Domination QoL: Halo Effect
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/wod13/datums/powers/discipline/dominate.dm
Labels: Enhancement, Refactor

#153 Less accident-prone Garou transformation
  code/_onclick/hud/werewolf.dm
Labels: Enhancement, Testing Evidence Required

#108 Simplemobs and Crinos Take Punch Damage, Other Punch Changes
  code/_onclick/other_mobs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/werewolf/werewolf.dm
  code/modules/mob/living/carbon/werewolf/werewolf_defense.dm
  code/modules/wod13/npcs/animal_defense.dm
Labels: Enhancement, TESTMERGE, Balance

#177 Fixed the handcannon cargo crates
  code/modules/wod13/cargo.dm
Labels: Enhancement, TESTMERGE, Balance

#154 You can now lock/unlock doors with rmb without keys in hand
  code/modules/wod13/structures/doors/vampdoor.dm
Labels: Enhancement, TESTMERGE, Balance

#171 Obfuscate changes!
  code/__DEFINES/sight.dm
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/__DEFINES/wod13/dcs/power_signals.dm
  code/_globalvars/traits.dm
  code/modules/mob/living/init_signals.dm
  code/modules/wod13/datums/powers/discipline/auspex.dm
  code/modules/wod13/datums/powers/discipline/celerity.dm
  code/modules/wod13/datums/powers/discipline/obfuscate.dm
Labels: Enhancement, TESTMERGE, Balance

#203 Removes SWAT NPCs from the game, and related code.
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/spaceman.dm
  code/modules/vtmb/frenzy.dm
  code/modules/vtmb/gamemodes/masquerade.dm
  code/modules/vtmb/ghoul_species.dm
  code/modules/vtmb/jobs/fbi.dm
  code/modules/vtmb/jobs/national_guard.dm
  code/modules/vtmb/jobs/police.dm
  code/modules/vtmb/jobs/prince.dm
  code/modules/vtmb/jobs/sheriff.dm
  code/modules/vtmb/jobs/swat.dm
  code/modules/vtmb/kuei_jin.dm
  code/modules/wod13/npc_movement.dm
  code/modules/wod13/npcroles.dm
  code/modules/wod13/onyxcombat.dm
  code/modules/wod13/procs.dm
Labels: Balance, Removal
