Repository The-Final-Nights/The-Final-Nights, pull requests merged in 2025-06, with the labels that each got.

#520 Stops clients from authenticating with the BYOND Pager.
  code/modules/client/client_defines.dm
Labels: TESTMERGE, Development

#518 [Port] Dead bodies now cool down to room temperatue
  code/modules/mob/living/carbon/life.dm
Labels: Enhancement, Balance

#497 Pyxis Medstation
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/electronics/machines/A_pyxis_stock.dm
  code/modules/vtmb/electronics/machines/B_pyxis_machine.dm
  code/modules/wod13/props.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/Pyxis.jsx
Labels: Enhancement, New Feature, TESTMERGE, Balance, Mapping, Icons, Administration, Sounds

#502 Dodge Fix
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/wod13/onyxcombat.dm
Labels: Enhancement, Balance

#491 We are Evil Whitelisters. We Whitelisted Evil maxxxing (Baali, Daughters of Cacophany, and True Brujah)
  code/modules/vtmb/vampire_clane/baali.dm
  code/modules/vtmb/vampire_clane/doc.dm
  code/modules/vtmb/vampire_clane/true_brujah.dm
Labels: Enhancement, Testing Evidence Required, Balance, Lore Team Approved

#528 no more roundend report popup
  code/__HELPERS/roundend.dm
Labels: Enhancement, Testing Evidence Required

#519 padded walls (wallpapers) and grates as a lattice type
  code/game/objects/structures/lattice.dm
  code/modules/wod13/tiles.dmi
  code/modules/wod13/wallcode.dm
Labels: New Feature, Icons

#530 [IDB IGNORE] Fixes some GAGs related runtimes
  code/datums/greyscale/config_types/greyscale_configs/greyscale_items.dm
  code/datums/greyscale/config_types/greyscale_configs/greyscale_objects.dm
  code/game/objects/items/melee/misc.dm
  code/modules/antagonists/eldritch_cult/eldritch_antag.dm
  code/modules/antagonists/eldritch_cult/eldritch_book.dm
  code/modules/antagonists/eldritch_cult/eldritch_effects.dm
  icons/effects/96x96.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/hydroponics/harvest.dmi
  icons/obj/weapons/cleric_mace.dmi
  icons/obj/weapons/ritual_weapon.dmi
  tgstation.dme
Labels: Enhancement, Icons

#512 Changed damage values and reworked quietus 4
  code/game/atom_defense.dm
  code/modules/wod13/datums/powers/discipline/quietus.dm
  code/modules/wod13/melee.dm
Labels: Enhancement, Balance

#433 Refactors blood packs and blood extractors
  _maps/map_files/Vampire/SanFrancisco.dmm
  _maps/map_files/Vampire/runtimetown.dmm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/cargo/packs.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/vtmb/electronics/machines/A_pyxis_stock.dm
  code/modules/vtmb/magic/pyramid.dm
  code/modules/vtmb/vampire_clane/tzimisce.dm
  code/modules/wod13/blood_extractor.dm
  code/modules/wod13/datums/powers/discipline/obtenebration.dm
  code/modules/wod13/decor.dm
  code/modules/wod13/items.dmi
  code/modules/wod13/items/drinkable_bloodpack.dm
  code/modules/wod13/items/narcotics/bweedpack.dm
  code/modules/wod13/items/narcotics/cokepack.dm
  code/modules/wod13/items/narcotics/meth/methpack.dm
  code/modules/wod13/items/narcotics/morphpack.dm
  code/modules/wod13/lefthand.dmi
  code/modules/wod13/machine_vending.dm
  code/modules/wod13/onfloor.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/packadulteration.dm
  code/modules/wod13/righthand.dmi
  tgstation.dme
  tools/UpdatePaths/Scripts/TFN Scripts/433_ blood_pack_changes.txt
Labels: Enhancement, Refactor, TESTMERGE, Mapping

#535 Fixed improper encoding on phone records, fixed runtime related to blood packs
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/vtmb/electronics/phones/phone.dm
Labels: Enhancement

#536 Griddle hotfix
  code/datums/components/grillable.dm
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
Labels: Enhancement, FUCK

#532 Fixes Signalers not working.
  code/__DEFINES/logging.dm
  code/_globalvars/logging.dm
  code/game/objects/items/devices/PDA/radio.dm
  code/modules/admin/verbs/secrets.dm
  code/modules/assembly/signaler.dm
  tgui/packages/tgui/interfaces/Signaler.jsx
  tgui/packages/tgui/interfaces/Signaler.tsx
Labels: Enhancement

#425 Curse/Gargoyle/Bloodwalk Ritual Rework
  code/__DEFINES/span.dm
  code/modules/mob/living/blood.dm
  code/modules/vtmb/magic/pyramid.dm
  code/modules/vtmb/vampire_clane/tzimisce.dm
  code/modules/wod13/datums/powers/discipline/thaumaturgy.dm
Labels: Enhancement, TESTMERGE, Balance, Lore Team Approved

#534 Window Destruction Overhaul
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/Vampire/SanFrancisco.dmm
  tools/UpdatePaths/Scripts/TFN Scripts/534_map_destruction.txt
Labels: Enhancement, Mapping

#537 Adds Custom Examine Text!
  code/modules/custom_examine_text/custom_examine_text.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/examine.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/TextInputModal.jsx
Labels: New Feature

#544 this should fix garou failing to return_to_corpse()
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/werewolf/transformation.dm
Labels: Enhancement

#555 Fixing heart sprites disappearing after a while
  code/modules/surgery/organs/heart.dm
Labels: Enhancement

#524 adds sabbat shovelhead npcs
  code/controllers/subsystem/humannpcpool.dm
  code/controllers/subsystem/rolling.dm
  code/datums/status_effects/status_effect.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/vtmb/frenzy.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/vtmb/vampire_clane/clane.dm
  code/modules/wod13/bloodsucking.dm
  code/modules/wod13/npc_aggression.dm
  code/modules/wod13/npc_movement.dm
  code/modules/wod13/npcs/sabbat_npc.dm
  code/modules/wod13/procs.dm
  tgstation.dme
Labels: New Feature, Balance

#546 removes a warning from main
  code/modules/wod13/datums/powers/discipline/thaumaturgy.dm
Labels: Enhancement, Development

#547 Ticked File Enforcement Fixes
  code/modules/asset_cache/assets/bibles.dm
  code/modules/cards/singlecard.dm
  code/modules/clothing/shoes/costume.dm
  code/modules/power/lighting/light_wallframes.dm
  tgstation.dme
Labels: Enhancement, Development

#559 Actually fixes bloodpacks for real this time
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/wod13/onfloor.dmi
Labels: Enhancement, Icons

#558 Changeling Updates and DNA fix port.
  code/__DEFINES/DNA.dm
  code/__HELPERS/dna.dm
  code/__HELPERS/sanitize_values.dm
  code/datums/dna.dm
  code/datums/status_effects/buffs.dm
  code/game/gamemodes/changeling/changeling.dm
  code/modules/antagonists/changeling/changeling.dm
  code/modules/antagonists/changeling/powers/mutations.dm
  code/modules/antagonists/changeling/powers/tiny_prick.dm
  code/modules/wod13/npc.dm
  icons/mob/actions/actions_changeling.dmi
Labels: Enhancement, Balance, Icons

#563 adds an anarchist flag
  code/modules/wod13/decor.dm
  code/modules/wod13/props.dmi
Labels: New Feature, Icons

#562 fixes an issue regarding examine block text
  code/modules/mob/mob.dm
Labels: Enhancement

#568 updated role bans
  code/modules/admin/sql_ban_system.dm
  html/admin/banpanel.css
Labels: Enhancement, Administration

#572 Bogatyr don't breach on latejoin
  code/modules/vtmb/jobs/bogatyr.dm
Labels: Enhancement

#522 Added Typhon's Beer for Setites to create (COMISSION)
  code/__DEFINES/food.dm
  code/datums/components/crafting/recipes.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/vtmb/ghoul_species.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/wod13/datums/powers/discipline/serpentis.dm
  code/modules/wod13/food.dm
  code/modules/wod13/items.dmi
  code/modules/wod13/onfloor.dmi
Labels: New Feature, Icons

#527 Reworked Fortitude and Iron Mountain to use Damage_Resistance
  code/modules/vtmb/chi_disciplines.dm
  code/modules/wod13/datums/powers/discipline/fortitude.dm
Labels: Enhancement, Balance

#538 Adds two new flaws, and reworks the Tremere clan curse to be a variant of one of the flaws.
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/datums/mind.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/vtmb/vampire_clane/tremere.dm
  code/modules/wod13/npc.dm
  code/modules/wod13/quirks.dm
Labels: Enhancement, New Feature

#584 Update README.md
  README.md
Labels: Enhancement

#570 renames a singualr species file
  code/modules/mob/living/carbon/human/_species.dm
  tgstation.dme
Labels: Enhancement

#573 Removes population based job scaling.
  code/controllers/subsystem/job_scaling.dm
  tgstation.dme
Labels: Removal

#583 Updates build.js
  tools/build/build.js
Labels: Enhancement, Development

#574 Whitelists Garou
  code/modules/vtmb/werewolf_species.dm
Labels: Enhancement, Administration

#517 Tweaks Necromancy
  code/__DEFINES/traits/declarations.dm
  code/__DEFINES/traits/sources.dm
  code/_globalvars/traits/_traits.dm
  code/controllers/subsystem/job.dm
  code/datums/keybinding/human.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/vtmb/magic/necromancy/_necrorune.dm
  code/modules/vtmb/magic/necromancy/necromancy_crafting.dm
  code/modules/vtmb/magic/necromancy/necromancy_items.dm
  code/modules/vtmb/magic/necromancy/necrorune/callthehungrydead.dm
  code/modules/vtmb/magic/necromancy/necrorune/death.dm
  code/modules/vtmb/magic/necromancy/necrorune/fireprotection.dm
  code/modules/vtmb/magic/necromancy/necrorune/insight.dm
  code/modules/vtmb/magic/necromancy/necrorune/locate.dm
  code/modules/vtmb/magic/necromancy/necrorune/truth.dm
  code/modules/vtmb/magic/necromancy/necrorune/zombie.dm
  code/modules/vtmb/vampire_clane/cappadocian.dm
  code/modules/vtmb/vampire_clane/giovanni.dm
  code/modules/vtmb/vampire_clane/nagaraja.dm
  code/modules/wod13/blood_extractor.dm
  code/modules/wod13/datums/powers/discipline/necromancy.dm
  code/modules/wod13/items.dmi
  code/modules/wod13/items/masquerade_contract.dm
  code/modules/wod13/mobs.dmi
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/onyxcombat/death.dm
  code/modules/wod13/procs.dm
  code/modules/wod13/sounds/necromancy1off.ogg
  code/modules/wod13/sounds/necromancy1on.ogg
  code/modules/wod13/sounds/necromancy2.ogg
  code/modules/wod13/sounds/necromancy3.ogg
  code/modules/wod13/sounds/necromancy4.ogg
  code/modules/wod13/sounds/necromancy5.ogg
  icons/hud/actions.dmi
  modular_tfn/modules/auspex_auras/auspex_auras.dm
  tgstation.dme
Labels: New Feature, TESTMERGE, Balance, Icons, Sounds, Lore Team Approved

#577 Craftable Arcane Tome
  code/modules/vtmb/magic/pyramid.dm
  code/modules/wod13/datums/powers/discipline/thaumaturgy.dm
Labels: Enhancement, Balance

#592 Fixes our Runtimes being missing
  code/__HELPERS/logging/_logging.dm
  code/__HELPERS/logging/admin.dm
  code/__HELPERS/logging/antagonists.dm
  code/__HELPERS/logging/attack.dm
  code/__HELPERS/logging/debug.dm
  code/__HELPERS/logging/dynamic.dm
  code/__HELPERS/logging/economy.dm
  code/__HELPERS/logging/game.dm
  code/__HELPERS/logging/manifest.dm
  code/__HELPERS/logging/mecha.dm
  code/__HELPERS/logging/mob.dm
  code/__HELPERS/logging/paper.dm
  code/__HELPERS/logging/pda.dm
  code/__HELPERS/logging/shuttle.dm
  code/__HELPERS/logging/subtle.dm
  code/__HELPERS/logging/talk.dm
  code/__HELPERS/logging/tool.dm
  code/__HELPERS/logging/ui.dm
  code/__HELPERS/logging/virus.dm
  code/controllers/globals.dm
  code/controllers/subsystem/dbcore.dm
  code/game/world.dm
  code/modules/admin/topic.dm
  code/modules/logging/log_category.dm
  code/modules/logging/log_holder.dm
  code/modules/mentor/mentor_admintools.dm
  code/modules/mob/mob_helpers.dm
  code/modules/vtmb/electronics/phones/phone.dm
Labels: Enhancement, FUCK, Development

#553 District Attorney (PD Lawyer) Human Role
  code/__DEFINES/jobs.dm
  code/modules/jobs/jobs.dm
  code/modules/paperwork/stamps.dm
  code/modules/vtmb/jobs/jobs.dm
  code/modules/vtmb/jobs/police.dm
  code/modules/wod13/items/keys/keys.dm
Labels: New Feature, Balance

#581 Late delivery (Adds an HK PSG1 + Ammo variants)
  code/__DEFINES/projectiles.dm
  code/modules/vtmb/gridventory.dm
  code/modules/wod13/48x32weapons.dmi
  code/modules/wod13/ammo.dmi
  code/modules/wod13/ammostack.dm
  code/modules/wod13/cargo.dm
  code/modules/wod13/guns.dm
  code/modules/wod13/lefthand.dmi
  code/modules/wod13/machine_vending.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/righthand.dmi
  code/modules/wod13/worn.dmi
Labels: New Feature, Balance

#600 Removes a random ass vault door I added by accident
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Enhancement, Mapping

#588 Endron Jobs QoL
  code/modules/vtmb/jobs/garou/poisonshore.dm
  code/modules/vtmb/jobs/jobs.dm
  code/modules/wod13/items.dmi
  code/modules/wod13/items/clothes/belt.dm
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/worn.dmi
Labels: Enhancement, Balance, Icons

#605 New corax flight!
  code/modules/mob/living/simple_animal/werewolf/lupus.dm
Labels: Enhancement, Balance
