Repository The-Final-Nights/The-Final-Nights, pull requests merged in 2025-07, with the labels that each got.

#609 Fixes the PSG1 Lefthand sprite.
  code/modules/wod13/lefthand.dmi
Labels: Enhancement, Icons

#521 Dominate 1 QOL and VOG sound reduction
  code/datums/brain_damage/special.dm
  code/modules/spells/spell_types/voice_of_god.dm
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/wod13/datums/actions/dominate_commands.dm
  code/modules/wod13/datums/powers/discipline/dominate.dm
  tgstation.dme
Labels: Enhancement, Balance

#540 More Blood Changes!
  code/__DEFINES/tfn/vtm_defines.dm
  code/__DEFINES/traits/vtm/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/game/atoms.dm
  code/game/machinery/iv_drip.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/client/preferences_savefile.dm
  code/modules/hydroponics/grown/kudzu.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/mob/living/blood.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/vtmb/ghoul_species.dm
  code/modules/vtmb/kindred_species.dm
  code/modules/vtmb/magic/pyramid.dm
  code/modules/wod13/items.dmi
  code/modules/wod13/npc.dm
  code/modules/wod13/npc_movement.dm
  code/modules/wod13/props.dmi
  code/modules/wod13/quirks.dm
  modular_tfn/master_files/icons/obj/bloodpack.dmi
  modular_tfn/modules/vitae/code/blood_bond.dm
  modular_tfn/modules/vitae/code/blood_extractor.dm
  modular_tfn/modules/vitae/code/blood_pack.dm
  modular_tfn/modules/vitae/code/embracing.dm
  modular_tfn/modules/vitae/code/ghouling.dm
  modular_tfn/modules/vitae/code/vitae.dm
  modular_tfn/modules/vitae/icons/blood_extractor.dmi
  modular_tfn/modules/vitae/readme.md
  tgstation.dme
Labels: Enhancement

#625 Have your cake and eat it too (Banu Jacket)
  code/modules/vtmb/jobs/primogen.dm
  code/modules/wod13/clothing.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
  modular_tfn/modules/banujacket/banujacket.dm
  modular_tfn/modules/banujacket/icons/banujacket.dmi
  tgstation.dme
Labels: New Feature, TESTMERGE, Icons

#624 Crinos HP Buff (Armor, you traitor...)
  code/modules/mob/living/simple_animal/werewolf/werewolf.dm
Labels: Enhancement, TESTMERGE, Balance

#632 Caine addition
  modular_tfn/modules/loadout/loadout_general.dm
Labels: Enhancement, New Feature

#643 Fixes Meleemods for Weapons
  code/_onclick/item_attack.dm
Labels: Enhancement, TESTMERGE, Balance

#620 Makes rage heal not stupid + fixes limping for everyone
  code/datums/wounds/_wounds.dm
  code/modules/vtmb/ghoul_species.dm
  code/modules/vtmb/werewolf/gifts.dm
  code/modules/wod13/datums/powers/discipline/bloodheal.dm
Labels: Enhancement, Balance

#630 Footstep override for catwalks
  code/__DEFINES/footsteps.dm
  code/datums/components/footstep.dm
  modular_tfn/modules/catwalk_footstep_overrides/code/footstep_override.dm
  modular_tfn/modules/catwalk_footstep_overrides/code/lattice.dm
  tgstation.dme
Labels: Enhancement, Refactor

#645 Curse of the Pomp Shotgun (Grammar fixes)
  code/modules/wod13/cargo.dm
  code/modules/wod13/guns.dm
  code/modules/wod13/items/stores/clothes.dm
  code/modules/wod13/lefthand.dmi
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/righthand.dmi
  code/modules/wod13/sounds/pump.ogg
  code/modules/wod13/worn.dmi
Labels: Enhancement

#652 The Gargoyle Unscrewing part 1
  code/modules/vtmb/vampire_clan/gargoyle.dm
Labels: Enhancement
